import { AlertTriangle, Scale, Info, Shield } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "./ui/alert";
import { Card } from "./ui/card";

interface InlineDisclaimerProps {
  type?: 'legal' | 'ai' | 'educational' | 'privacy' | 'data';
  variant?: 'default' | 'compact' | 'prominent';
  className?: string;
}

export function InlineDisclaimer({ 
  type = 'legal', 
  variant = 'default',
  className = '' 
}: InlineDisclaimerProps) {
  const disclaimers = {
    legal: {
      icon: Scale,
      title: 'Not Legal Advice',
      description: 'This information is for educational purposes only and does not constitute legal advice. Laws vary by state and individual circumstances. Always consult with a qualified attorney licensed in your jurisdiction for advice specific to your case.',
      bgColor: 'bg-amber-50 dark:bg-amber-950/30',
      borderColor: 'border-amber-200 dark:border-amber-800',
      textColor: 'text-amber-900 dark:text-amber-100',
      descColor: 'text-amber-800 dark:text-amber-200',
    },
    ai: {
      icon: Info,
      title: 'AI-Generated Content',
      description: 'This content is generated by artificial intelligence and should be reviewed carefully. AI can make mistakes or provide incomplete information. Verify all critical information with official sources and qualified professionals.',
      bgColor: 'bg-blue-50 dark:bg-blue-950/30',
      borderColor: 'border-blue-200 dark:border-blue-800',
      textColor: 'text-blue-900 dark:text-blue-100',
      descColor: 'text-blue-800 dark:text-blue-200',
    },
    educational: {
      icon: Shield,
      title: 'Educational Tool Only',
      description: 'This is an educational tool designed to help you understand CPS processes and identify potential issues. It does not replace professional legal representation or advice from qualified experts.',
      bgColor: 'bg-purple-50 dark:bg-purple-950/30',
      borderColor: 'border-purple-200 dark:border-purple-800',
      textColor: 'text-purple-900 dark:text-purple-100',
      descColor: 'text-purple-800 dark:text-purple-200',
    },
    privacy: {
      icon: Shield,
      title: 'Privacy & Data Security',
      description: 'Your case information is sensitive. When using cloud storage, data is encrypted in transit and at rest. For maximum privacy, use local storage mode. Never share login credentials or upload documents containing information you want to keep completely private.',
      bgColor: 'bg-green-50 dark:bg-green-950/30',
      borderColor: 'border-green-200 dark:border-green-800',
      textColor: 'text-green-900 dark:text-green-100',
      descColor: 'text-green-800 dark:text-green-200',
    },
    data: {
      icon: AlertTriangle,
      title: 'Data Accuracy',
      description: 'You are responsible for the accuracy of information you enter. This tool cannot verify the accuracy of your inputs. Ensure all dates, names, and details are correct as inaccurate information may affect your case strategy.',
      bgColor: 'bg-red-50 dark:bg-red-950/30',
      borderColor: 'border-red-200 dark:border-red-800',
      textColor: 'text-red-900 dark:text-red-100',
      descColor: 'text-red-800 dark:text-red-200',
    },
  };

  const config = disclaimers[type];
  const Icon = config.icon;

  if (variant === 'compact') {
    return (
      <div 
        className={`flex items-start gap-2 p-2 rounded-md ${config.bgColor} ${config.borderColor} border text-xs ${className}`}
        role="note"
        aria-label={config.title}
      >
        <Icon className={`w-3 h-3 ${config.textColor} flex-shrink-0 mt-0.5`} aria-hidden="true" />
        <span className={config.descColor}>
          <strong className={config.textColor}>{config.title}:</strong> {config.description}
        </span>
      </div>
    );
  }

  if (variant === 'prominent') {
    return (
      <Card 
        className={`p-4 sm:p-6 ${config.bgColor} ${config.borderColor} border-2 shadow-lg ${className}`}
        role="alert"
        aria-live="polite"
      >
        <div className="flex items-start gap-3">
          <div className={`w-10 h-10 ${config.bgColor} rounded-lg flex items-center justify-center flex-shrink-0 border-2 ${config.borderColor}`}>
            <Icon className={`w-5 h-5 ${config.textColor}`} aria-hidden="true" />
          </div>
          <div className="flex-1 min-w-0">
            <h3 className={`text-base sm:text-lg font-bold ${config.textColor} mb-2`}>
              ⚠️ {config.title}
            </h3>
            <p className={`text-sm ${config.descColor} leading-relaxed`}>
              {config.description}
            </p>
          </div>
        </div>
      </Card>
    );
  }

  return (
    <Alert 
      className={`${config.bgColor} ${config.borderColor} border ${className}`}
      role="note"
      aria-label={config.title}
    >
      <Icon className={`h-4 w-4 ${config.textColor}`} aria-hidden="true" />
      <AlertTitle className={config.textColor}>{config.title}</AlertTitle>
      <AlertDescription className={config.descColor}>
        {config.description}
      </AlertDescription>
    </Alert>
  );
}

// Comprehensive disclaimer footer component
export function DisclaimerFooter({ className = '' }: { className?: string }) {
  return (
    <footer 
      className={`mt-8 pt-6 border-t border-border ${className}`}
      role="contentinfo"
      aria-label="Legal disclaimers and notices"
    >
      <div className="space-y-4">
        <InlineDisclaimer type="legal" variant="compact" />
        <div className="text-xs text-muted-foreground space-y-2">
          <p>
            <strong>No Attorney-Client Relationship:</strong> Use of this tool does not create an attorney-client relationship. 
            You should not rely on this tool as a substitute for professional legal advice from an attorney licensed in your state.
          </p>
          <p>
            <strong>Accuracy:</strong> While we strive for accuracy, we make no warranties or guarantees about the accuracy, 
            completeness, or timeliness of the information provided. Laws change frequently and vary by jurisdiction.
          </p>
          <p>
            <strong>Limitation of Liability:</strong> We are not liable for any damages or losses arising from your use of this tool 
            or reliance on information provided. Your use of this tool is at your own risk.
          </p>
          <p className="font-semibold">
            © {new Date().getFullYear()} The CPS Punisher. For educational and informational purposes only.
          </p>
        </div>
      </div>
    </footer>
  );
}
